get http://localhost:3457/appointments

###

get http://localhost:3457/appointments/12

###

post http://localhost:3457/appointments
Content-Type: application/json

{"dateTime": "2020-03-18T17:00:00Z", "firstName": "Anna", "secondName": "Grey", "product": "Shellac", "phoneNumber": "3456789012"}